version: '3.4'

services:
  nats:
    image: nats:2.12.2
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222", "-sd", "/data"]
    volumes:
      - nats-data:/data

  subscriber:
    build:
      context: ./NatsSubscriber/NatsSubscriber
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - NATS_SUBJECT=pago.saludo
      - NATS_DURABLE=SUB_PAGOS
 

  publisher:
    build:
      context: ./NatsPublisher/NatsPublisher
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    restart: "no"

volumes:
  nats-data:
